#Ejemplo numpy

In [1]:
import numpy as np

a = np.array([1,2,3]) #Arreglo unidimencional
print(a,"\n")
b=np.array([(1,2,3),(4,5,6)]) #Arreglo bidimencional
print(b)


[1 2 3] 

[[1 2 3]
 [4 5 6]]


In [18]:
#Crear matrices de 1 (3 filas y 5 columnas)
matriz1 = np.ones((3,5))
print(matriz1,'\n')

#Crear matrices de 0 (3 filas y 5 columnas)
matriz0 = np.zeros((3,5))
print(matriz0,'\n')

#Crar matrices con un solo calor en todas las posciciones (3 filas y 5 columnas)
matriz_igual = np.full((3,5),5)
print(matriz_igual,'\n')

#Crear matriz con numeros aleatorios (3 filas y 5 columnas)
matriz_random = np.random.random((3,5))
print(matriz_random,'\n')

#Crar matriz unidimencional con valores que se separan uniformemente
llenarM = np.arange(0,50,10) # inicia en 0 hasta 40 y va de 10 en 10
print(llenarM,'\n')

#Crea matriz unidimencional con valores que se separan uniformemente
llenarM = np.linspace(0,50,10) # inicia en 0 hasta 50 y creame 10 numeros
print(llenarM,'\n')



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] 

[[0.89937388 0.8278793  0.61053478 0.77335238 0.1370551 ]
 [0.62140053 0.30335475 0.01473508 0.2032619  0.01195641]
 [0.21676934 0.1030371  0.63226203 0.73547724 0.54040434]] 

[ 0 10 20 30 40] 

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ] 



In [ ]:
#Crea una matriz identidad
matriz_identidad = np.eye(4,4)
print(matriz_identidad,'\n')

#Parametros de las matrices
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim, "Es el tamaño del arreglo")
print(b.dtype, "El tipo de dato del arreglo")
print(b.size, "La suma de los arreglos")
print(b.shape, "\n")

#reshape = ordena el arreglo
a =b.reshape(3,2)
print(a,'\n')

#Imprimir el elemendo que es igual a 9
a1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a1[1,2])
#Imprimir los valores de la primera fila
print(a1[0,:])


In [ ]:
c = np.array(((1,2,3,4,5,6),(7,8,9,10,11,12)))
print(c)
print(c.min(),"Minimo entre las dos matrices")
print(c.max(),"Maximo entre las dos matrices")
print(c.sum(),"Suma todos los valores")
print(c.sum(0),"Suma las columnas (1+7, 2+8 etc..)")
print(c.sum(1),"Suma los valores del primer y segundo arreglo por separado")

#desviación estándar 
print(np.std(c))

In [ ]:
A=np.array(((1,2),(3,4)))
B = np.array(((9,8),(7,6)))

print(A,'\n')
print(B,'\n')
print(A+B,'\n')
print(A-B,'\n')
print(A*B,'\n')
print(A.dot(B),'\n') #dot = multiplicacion de matrices

#Pandas

In [ ]:
import numpy as np
import pandas as pd
data = np.array([["","Nombre","Edad"],["Estudiante","Ana",12],["Estudiante2","Maria",9]])
df = pd.DataFrame(data)
print(df,'\n')
print(pd.DataFrame(data=data[1:,1:], index= data[1:,0],columns=data[0,1:]))
print("Forma:", df.shape)
print("Estadisticas: \n", df.describe())



In [ ]:
data2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df2= pd.DataFrame(data2)

print("Estadisticas :\n ", df2.describe(),"\n")
print("Media :\n ", df2.mean())

In [52]:
print(df2.max())
print(df2.min())

0    7
1    8
2    9
dtype: int64
0    1
1    2
2    3
dtype: int64
